//! Compile-time codegen: walks `vendor/ldnoobw/`, validates drift against a
//! static allowlist/skip list, and emits `$OUT_DIR/generated_terms.rs` with
//! `LIST_VERSION` and `TERMS` for `include!` at the consumer.

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::process::Command;

const ALLOWLIST: &[&str] = &[
    "ar", "cs", "da", "de", "en", "eo", "es", "fa", "fi", "fil", "fr", "hi", "hu", "it", "ja",
    "kab", "ko", "nl", "no", "pl", "pt", "ru", "sv", "th", "tlh", "tr", "zh",
];

const SKIP_LIST: &[&str] = &["fr-CA-u-sd-caqc", "LICENSE", "README.md", "USERS.md"];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=vendor/ldnoobw");
    println!("cargo:rerun-if-changed=.git/modules/vendor/ldnoobw/HEAD");

    let vendor = Path::new("vendor/ldnoobw");
    assert!(
        vendor.is_dir(),
        "vendor/ldnoobw is missing — run: git submodule update --init --recursive"
    );

    let sha = read_submodule_sha(vendor);
    let files = enumerate(vendor);
    validate(&files);
    let terms = load_terms(vendor);
    emit(&sha, &terms);
}

fn read_submodule_sha(vendor: &Path) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(vendor)
        .args(["rev-parse", "HEAD"])
        .output()
        .expect("failed to invoke `git` to read LDNOOBW submodule SHA");
    assert!(
        output.status.success(),
        "`git -C {} rev-parse HEAD` failed: {}",
        vendor.display(),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout)
        .expect("submodule SHA is not UTF-8")
        .trim()
        .to_string()
}

fn enumerate(vendor: &Path) -> BTreeSet<String> {
    fs::read_dir(vendor)
        .unwrap_or_else(|e| panic!("read_dir({}): {e}", vendor.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let ft = entry.file_type().ok()?;
            if !ft.is_file() {
                return None;
            }
            let name = entry.file_name().into_string().ok()?;
            // Submodules have a `.git` gitfile at the root; ignore any dotfiles.
            if name.starts_with('.') {
                return None;
            }
            Some(name)
        })
        .collect()
}

fn validate(files: &BTreeSet<String>) {
    let allow: BTreeSet<&str> = ALLOWLIST.iter().copied().collect();
    let skip: BTreeSet<&str> = SKIP_LIST.iter().copied().collect();

    let overlap: Vec<&&str> = allow.intersection(&skip).collect();
    assert!(
        overlap.is_empty(),
        "ALLOWLIST and SKIP_LIST overlap: {overlap:?}"
    );

    let missing: Vec<&&str> = allow
        .iter()
        .filter(|code| !files.contains(**code))
        .collect();
    assert!(
        missing.is_empty(),
        "LDNOOBW drift: allowlisted languages with no file at pinned SHA: {missing:?}"
    );

    let unknown: Vec<&String> = files
        .iter()
        .filter(|f| !allow.contains(f.as_str()) && !skip.contains(f.as_str()))
        .collect();
    assert!(
        unknown.is_empty(),
        "LDNOOBW drift: files in vendor/ldnoobw not in allowlist or skip list: {unknown:?}"
    );
}

fn load_terms(vendor: &Path) -> Vec<(String, Vec<String>)> {
    let mut out: Vec<(String, Vec<String>)> = ALLOWLIST
        .iter()
        .map(|code| {
            let path = vendor.join(code);
            let raw = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            let mut terms: Vec<String> = raw
                .lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty())
                .collect();
            terms.sort();
            terms.dedup();
            assert!(
                !terms.is_empty(),
                "LDNOOBW drift: language file {} is empty",
                path.display()
            );
            ((*code).to_string(), terms)
        })
        .collect();
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn emit(sha: &str, terms: &[(String, Vec<String>)]) {
    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("generated_terms.rs");

    let mut s = String::new();
    writeln!(s, "// Auto-generated by build.rs. Do not edit.").unwrap();
    writeln!(s, "pub const LIST_VERSION: &str = \"{sha}\";").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "pub static TERMS: ::phf::Map<&'static str, &'static [&'static str]> = ::phf::phf_map! {{"
    )
    .unwrap();
    for (code, words) in terms {
        write!(s, "    \"{code}\" => &[").unwrap();
        for (i, w) in words.iter().enumerate() {
            if i > 0 {
                s.push_str(", ");
            }
            write!(s, "{w:?}").unwrap();
        }
        writeln!(s, "],").unwrap();
    }
    writeln!(s, "}};").unwrap();

    fs::write(&out_path, s).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}
